name: create_theme
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^4.2.0
  build: ^2.3.0
  create_theme_annotation:
    git: 
      url: https://github.com/SuperPenguin/create_theme.git
      path: packages/create_theme_annotation
  source_gen: ^1.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
