name: create_theme
description: Code generator for flutter ThemeExtension
version: 0.5.0
homepage: https://github.com/SuperPenguin/create_theme
repository: https://github.com/SuperPenguin/create_theme
issue_tracker: https://github.com/SuperPenguin/create_theme/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.3.0
  create_theme_annotation: ^0.4.0
  source_gen: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.5
