name: create_theme_annotation
description: A starting point for Dart libraries or applications.
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
