name: create_theme_annotation
description: Annotation for create_theme code generator
version: 0.6.0
homepage: https://github.com/SuperPenguin/create_theme
repository: https://github.com/SuperPenguin/create_theme
issue_tracker: https://github.com/SuperPenguin/create_theme/issues

environment:
  sdk: ^3.8.0

dev_dependencies:
  lints: ^6.0.0
